name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python src/main.py
          
          echo "## Model metrics" > report.md
          cat report/metrics.txt >> report.md
          
          echo "## Data viz" >> report.md
          cml-publish report/feature_importance.png --md >> report.md
          cml-publish report/residuals.png --md >> report.md
          
          cml-send-comment report.md
